roles:
  finance:
    allowed_tools:
      - get_daily_revenue
      - get_revenue_by_sku
      - find_missing_skus_yesterday
      - get_data_freshness
      - retrieve_docs
      - send_alert

  ops:
    allowed_tools:
      - get_daily_revenue
      - get_data_freshness
      - retrieve_docs
      - send_alert
